/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.schmix.AddressBook', null, global);
goog.exportSymbol('proto.schmix.Person', null, global);
goog.exportSymbol('proto.schmix.Person.PhoneNumber', null, global);
goog.exportSymbol('proto.schmix.Person.PhoneType', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.schmix.Person = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.schmix.Person.repeatedFields_, null);
};
goog.inherits(proto.schmix.Person, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.schmix.Person.displayName = 'proto.schmix.Person';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.schmix.Person.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.schmix.Person.prototype.toObject = function(opt_includeInstance) {
  return proto.schmix.Person.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.schmix.Person} msg The msg instance to transform.
 * @return {!Object}
 */
proto.schmix.Person.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: msg.getName(),
    id: msg.getId(),
    email: msg.getEmail(),
    phoneList: jspb.Message.toObjectList(msg.getPhoneList(),
    proto.schmix.Person.PhoneNumber.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.schmix.Person}
 */
proto.schmix.Person.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.schmix.Person;
  return proto.schmix.Person.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.schmix.Person} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.schmix.Person}
 */
proto.schmix.Person.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 4:
      var value = new proto.schmix.Person.PhoneNumber;
      reader.readMessage(value,proto.schmix.Person.PhoneNumber.deserializeBinaryFromReader);
      msg.getPhoneList().push(value);
      msg.setPhoneList(msg.getPhoneList());
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.schmix.Person} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.schmix.Person.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.schmix.Person.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.schmix.Person.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getId();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = this.getEmail();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = this.getPhoneList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.schmix.Person.PhoneNumber.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.schmix.Person} The clone.
 */
proto.schmix.Person.prototype.cloneMessage = function() {
  return /** @type {!proto.schmix.Person} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.schmix.Person.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.schmix.Person.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int32 id = 2;
 * @return {number}
 */
proto.schmix.Person.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.schmix.Person.prototype.setId = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string email = 3;
 * @return {string}
 */
proto.schmix.Person.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.schmix.Person.prototype.setEmail = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * repeated PhoneNumber phone = 4;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.schmix.Person.PhoneNumber>}
 */
proto.schmix.Person.prototype.getPhoneList = function() {
  return /** @type{!Array.<!proto.schmix.Person.PhoneNumber>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.schmix.Person.PhoneNumber, 4));
};


/** @param {Array.<!proto.schmix.Person.PhoneNumber>|undefined} value  */
proto.schmix.Person.prototype.setPhoneList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


proto.schmix.Person.prototype.clearPhoneList = function() {
  this.setPhoneList([]);
};


/**
 * @enum {number}
 */
proto.schmix.Person.PhoneType = {
  MOBILE: 0,
  HOME: 1,
  WORK: 2
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.schmix.Person.PhoneNumber = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.schmix.Person.PhoneNumber, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.schmix.Person.PhoneNumber.displayName = 'proto.schmix.Person.PhoneNumber';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.schmix.Person.PhoneNumber.prototype.toObject = function(opt_includeInstance) {
  return proto.schmix.Person.PhoneNumber.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.schmix.Person.PhoneNumber} msg The msg instance to transform.
 * @return {!Object}
 */
proto.schmix.Person.PhoneNumber.toObject = function(includeInstance, msg) {
  var f, obj = {
    number: msg.getNumber(),
    type: msg.getType()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.schmix.Person.PhoneNumber}
 */
proto.schmix.Person.PhoneNumber.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.schmix.Person.PhoneNumber;
  return proto.schmix.Person.PhoneNumber.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.schmix.Person.PhoneNumber} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.schmix.Person.PhoneNumber}
 */
proto.schmix.Person.PhoneNumber.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNumber(value);
      break;
    case 2:
      var value = /** @type {!proto.schmix.Person.PhoneType} */ (reader.readEnum());
      msg.setType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.schmix.Person.PhoneNumber} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.schmix.Person.PhoneNumber.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.schmix.Person.PhoneNumber.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.schmix.Person.PhoneNumber.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getNumber();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.schmix.Person.PhoneNumber} The clone.
 */
proto.schmix.Person.PhoneNumber.prototype.cloneMessage = function() {
  return /** @type {!proto.schmix.Person.PhoneNumber} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string number = 1;
 * @return {string}
 */
proto.schmix.Person.PhoneNumber.prototype.getNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.schmix.Person.PhoneNumber.prototype.setNumber = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional PhoneType type = 2;
 * @return {!proto.schmix.Person.PhoneType}
 */
proto.schmix.Person.PhoneNumber.prototype.getType = function() {
  return /** @type {!proto.schmix.Person.PhoneType} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {!proto.schmix.Person.PhoneType} value  */
proto.schmix.Person.PhoneNumber.prototype.setType = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.schmix.AddressBook = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.schmix.AddressBook.repeatedFields_, null);
};
goog.inherits(proto.schmix.AddressBook, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.schmix.AddressBook.displayName = 'proto.schmix.AddressBook';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.schmix.AddressBook.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.schmix.AddressBook.prototype.toObject = function(opt_includeInstance) {
  return proto.schmix.AddressBook.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.schmix.AddressBook} msg The msg instance to transform.
 * @return {!Object}
 */
proto.schmix.AddressBook.toObject = function(includeInstance, msg) {
  var f, obj = {
    personList: jspb.Message.toObjectList(msg.getPersonList(),
    proto.schmix.Person.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.schmix.AddressBook}
 */
proto.schmix.AddressBook.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.schmix.AddressBook;
  return proto.schmix.AddressBook.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.schmix.AddressBook} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.schmix.AddressBook}
 */
proto.schmix.AddressBook.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.schmix.Person;
      reader.readMessage(value,proto.schmix.Person.deserializeBinaryFromReader);
      msg.getPersonList().push(value);
      msg.setPersonList(msg.getPersonList());
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.schmix.AddressBook} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.schmix.AddressBook.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.schmix.AddressBook.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.schmix.AddressBook.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getPersonList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.schmix.Person.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.schmix.AddressBook} The clone.
 */
proto.schmix.AddressBook.prototype.cloneMessage = function() {
  return /** @type {!proto.schmix.AddressBook} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated Person person = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.schmix.Person>}
 */
proto.schmix.AddressBook.prototype.getPersonList = function() {
  return /** @type{!Array.<!proto.schmix.Person>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.schmix.Person, 1));
};


/** @param {Array.<!proto.schmix.Person>|undefined} value  */
proto.schmix.AddressBook.prototype.setPersonList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.schmix.AddressBook.prototype.clearPersonList = function() {
  this.setPersonList([]);
};


goog.object.extend(exports, proto.schmix);
